services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: ./.env
    networks:
      - backend
    volumes:
      - postgresql:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    env_file: ./.env
    command:
      - --changelog-file=db.master-changelog.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    networks:
      - backend
    volumes:
      - ./db/migrations:/liquibase/changelog

  prometheus:
    build:
      context: .
      dockerfile: prometheus.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_provisioning_data:/etc/grafana/provisioning


volumes:
  postgresql: { }
  prometheus_data: { }
  grafana_data: { }
  grafana_provisioning_data: { }

networks:
  backend: { }
