app:
  kafka-config-info:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    updates-topic:
      name: scrapper.updates
      partitions: 2
      replicas: 2
  use-queue: false

spring:
  application:
    name: financial-support
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: "/swagger-ui"

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
